### ISSUE TITLE
Showing DOMException error in Angular 6 with showModal option to true.

### ISSUE THREAD

**Issue by Shofol** [crabbly/Print.js#269]
Hello, I am trying to print a pdf on Button click. But after clicking the button it is throwing this error. 

```
ERROR DOMException: Blocked a frame with origin "http://localhost:4200" from accessing a cross-origin frame.
at performPrint (http://localhost:4200/modules-deposit-dashboard-deposit-dashboard-module.js:1025:33)
at finishPrint (http://localhost:4200/modules-deposit-dashboard-deposit-dashboard-module.js:1061:5)
at HTMLIFrameElement.printFrame.onload [as __zone_symbol__ON_PROPERTYload] (http://localhost:4200/modules-deposit-dashboard-deposit-dashboard-module.js:980:11)
at HTMLIFrameElement.wrapFn (http://localhost:4200/polyfills.js:12361:39)
at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:11594:31)
at Object.onInvokeTask (http://localhost:4200/vendor.js:42637:33)
at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:11593:36)
at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:4200/polyfills.js:11361:47)
at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (http://localhost:4200/polyfills.js:11669:34)
at invokeTask (http://localhost:4200/polyfills.js:12713:14)
```

I've set showModal to true and then it is showing this error-
`Access to XMLHttpRequest at 'http://www.pdf995.com/samples/pdf.pdf' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Live at Stackblitz-
https://print-js-outer-link.stackblitz.io
Editor Mode: https://stackblitz.com/edit/print-js-outer-link

**Comment by crabbly** [comment]
Hi @Shofol, the `showModal` should force the lib to pre-load the pdf document, preventing this issue.

The Stackblitz link above doesn't include / use the print.js library. Could you update it replicating the issue? Thank you.

**Comment by Shofol** [comment]
I have figured out the problem. 
**This is nothing but CORS issue.**

> When we want to request an external link other than the project scope then the requesting site's server may stop Cross-Origin requests. We need to handle it from our server side. 

I have run the same Stackblitz code with a CORS plugin enabled on Chrome. 

Thank you @crabbly for your great effort. Good luck.

![capture](https://user-images.githubusercontent.com/30428153/50625330-b41bd000-0f51-11e9-86cb-1dd0b8a7c404.JPG)
