### ISSUE TITLE
Reference Error

### ISSUE THREAD

**Issue by joonwkim** [crabbly/Print.js#706]
⨯ node_modules/print-js/dist/print.js (10:1) @ eval
 ⨯ ReferenceError: window is not defined
    at __webpack_require__ (/home/ubuntu/menusvc/.next/server/webpack-runtime.js:33:42)
    at eval (./app/navMenu/printOrders/page.tsx:7:66)
    at (ssr)/./app/navMenu/printOrders/page.tsx (/home/ubuntu/menusvc/.next/server/app/navMenu/printOrders/page.js:183:1)
    at __webpack_require__ (/home/ubuntu/menusvc/.next/server/webpack-runtime.js:33:42)
    at JSON.parse (<anonymous>)

**Comment by Redmega** [comment]
Duplicate of #542
